name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: released

env:
  CI_REQ_DOTNET_SDK_VER: 5.0.100

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}
          
      - uses: microsoft/setup-msbuild@v1.0.2

      # Build each tfm separately since building all requires too much disk space
      - name: Build dnSpy (.NET Framework)
        shell: pwsh
        run: |
          .\build.ps1 netframework
          New-Item -ItemType Directory -Path C:\builtfiles -Force > $null
          Compress-Archive -Path D:\a\dnSpyex\* -DestinationPath C:\builtfiles\dnSpy-netframework.zip
          .\clean-all.cmd
          
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          name: dnSpy-netframework
          path: C:\builtfiles\dnSpy-netframework.zip
          if-no-files-found: error
